import Head from 'next/head'
import Image from 'next/image'
import { YouTubeVideo } from '../components/youtube-video'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Más para ver</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles['main']}>

        <div className={styles['right']}>
          <h3 className={styles['title']}>Canales</h3>
          <div className={styles['channels']}>
            <button className={styles['channel']}>Canal 1</button>
            <button className={styles['channel']}>Canal 2</button>
            <button className={styles['channel']}>Canal 3</button>
            <button className={styles['channel']}>Canal 4</button>
            <button className={styles['channel']}>Canal 5</button>
          </div>
        </div>

        <div className={styles['center']}>
          <YouTubeVideo videoId='O3bhL1gPdxM' />
        </div>

        <div className={styles['left']} >
          <iframe
            src="https://www.twitch.tv/embed/tinoburgos/chat?parent=localhost"
            height="100%"
            width="100%"
            allowFullScreen={true}>
          </iframe>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
